name: CI

on: [push]

jobs:
  hello:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
    - run: echo Hello, today is $TODAY
    