name: CI

on: [push]

jobs:
  hello:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
      echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
      echo Hello, today is $TODAY