name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  hello:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
    - run: echo Hello, today is $TODAY
    